name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo history is checked out

      - name: Ensure clean git state
        run: git reset --hard && git clean -fdx

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Verify required dependencies
        run: pnpm list vitest eslint || echo "Missing dependencies, ensure they are in package.json"

      - name: Publish
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
